version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  test:
    resource_class: large
    executor:
      name: node/default
      tag: lts
    steps:
      - checkout
      - node/install:
          node-version: 20

      - run: npm <%= (type === "lib") ? "install" : "ci" %>
      - run: npm run build
      - run: npm test
      - run: npm run lint

  release:
    resource_class: large
    executor:
      name: node/default
      tag: lts
    steps:
      - checkout
      - node/install:
          node-version: 20

      - run: npm <%= (type === "lib") ? "install" : "ci" %>
      - run: npm run build
<% if (type === "lib") { -%>
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc
<% } -%>
      - run: npm run release

workflows:
  version: 2.1
  build-and-release:
    jobs:
      # Run when any branches & tags pushed
      - test:
          filters:
            tags:
              only: /.*/
      - release:
          filters:
            tags:
              only: /^v.*/
            # By default, release runs on push to any branches.
            # To avoid running release, it is required to ignore all branches here.
            branches:
              ignore: /.*/
          requires:
            - test
