version: 2.1

executors:
  default:
    working_directory: ~/<%= name %>
    docker:
      - image: circleci/node:<%= owner === "personal" ? "latest" : "10-stretch" %>

commands:
  init:
    steps:
      - checkout
<% if (type === "lib") { -%>
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
<% } else if (type === "app") { -%>
      - run: npm ci
<% } -%>

jobs:
  build:
    executor:
      name: default
    steps:
      - init
      - run:
          name: test
          command: npm test && npm run lint

  release:
    executor:
      name: default
    steps:
      - init
      <% if (type === "lib") { %>
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc
      <% } %>
      - run: npm run release
workflows:
  version: 2.1
  build-and-release:
    jobs:
      - build
      - release:
          filters:
            branches:
              only:
                - master
          requires:
            - build
